### ISSUE TITLE
Excepció al carregar una ontologia

### ISSUE THREAD

**Issue by opengeekv2** [kemlg/owls2wsdl#1]
Hola, soy Marc Mauri uno de vuestros alumnos de ECSDI

Me he encontrado un error al intentar importar la ontologia de dominio en owls2wsdl, no se si es porque hay algo en mi ontologia que no esta bien (aunque la editamos con Protégé) o si es un error de la aplicación. Podriais echarle un ojo?

La ontologia que estoy intentando importar la podeis importar des de esta URL:
http://medicinaesportivaontologies.bitbucket.org/domini.owl

Muchas gracias

Os copio el log de la aplicación a partir de una property antes que reviente:

PROPERTY: http://medicinaesportivaontologies.bitbucket.org/negoci.owl#import(RANGE: http://www.w3.org/2001/XMLSchema#float)
DOMAIN: http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu
[i] DOMAIN : http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu
[i] DECLARING CLASS: http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu
[i] getOntClassContainer http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu
[i] check registeredDatatypes key: http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu
[I](http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu) http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu_4
[i] register individualList for http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu
[i] OntClassContainer for class (http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu) created. Added to KB.
[i] Add DATATYPE-PROPERTY import to DECLARING class (http://medicinaesportivaontologies.bitbucket.org/negoci.owl#Preu)
java.lang.IllegalArgumentException: Cannot get() ontology value with a null URI
        at com.hp.hpl.jena.ontology.impl.OntModelImpl.findByURIAs(OntModelImpl.java:2760)
        at com.hp.hpl.jena.ontology.impl.OntModelImpl.getOntClass(OntModelImpl.java:869)
        at de.dfki.dmas.owls2wsdl.parser.DatatypeParser.collectDatatypeProperties(DatatypeParser.java:740)
        at de.dfki.dmas.owls2wsdl.parser.DatatypeParser.parse(DatatypeParser.java:335)
        at de.dfki.dmas.owls2wsdl.parser.DatatypeParser.parse(DatatypeParser.java:219)
        at de.dfki.dmas.owls2wsdl.core.Project.importDatatypes(Project.java:218)
        at de.dfki.dmas.owls2wsdl.gui.GUIActionListener.actionPerformed(GUIActionListener.java:712)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.Component.processMouseEvent(Component.java:6505)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
        at java.awt.Component.processEvent(Component.java:6270)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4861)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4687)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4687)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:729)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:688)
        at java.awt.EventQueue$3.run(EventQueue.java:686)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:702)
        at java.awt.EventQueue$4.run(EventQueue.java:700)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:699)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[u] ProjectDetailPanel
[i] Ont Count: 0
[u] update ServiceDetailPanel: domini.owl parsed.
[u] update ServiceDetailPanel, Runtime: datatype model changed.
[u] Update StatusTable
[AbstractDatatypeListModel] size 0
[u] update StatusBar: de.dfki.dmas.owls2wsdl.gui.RuntimeModel@673c2a08
[u] ToolBar - GuiStatusModel
[AbstractDatatypeListModel] size 0
Current Directory: /home/opengeek/Documents/ECSDI/Practica/Entrega3/repo/medicinaesportivaontologies.bitbucket.org

**Comment by tranchis** [comment]
Bones,

El problema ve d'aquí:

``` xml
<owl:DatatypeProperty rdf:ID="divisa">
  <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#FunctionalProperty"/>
  <rdfs:range>
    <owl:DataRange>
      <owl:oneOf rdf:parseType="Resource">
        <rdf:rest rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"/>
        <rdf:first rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
        >€</rdf:first>
      </owl:oneOf>
    </owl:DataRange>
  </rdfs:range>
  <rdfs:domain rdf:resource="#Preu"/>
</owl:DatatypeProperty>
```

owls2wsdl, com haurà de convertir a un schema xml, espera només un tipus de dada per DatatypeProperty. En aquest cas tenim una llista de possibilitats (oneOf), i com no espera una llista, peta, ja que hauria d'haver-hi un rdf:datatype a dins del tag rdfs:range.

Diria que és un bug múltiple: Protégé falla en exportar (això no té sentit: rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil") i owls2wsdl falla en no processar la llista per agafar almenys alguna de les possibilitats. El segon cas el puc intentar arreglar durant la setmana.

**Comment by tranchis** [comment]
Per cert, m'oblidava de comentar que una possible manera d'arreglar-ho temporalment és modificar el .owl a mà per evitar que declari un DataRange i ficar el datatype directament al rdfs:range.

**Comment by tranchis** [comment]
Solucionat amb el commit: https://github.com/kemlg/owls2wsdl/commit/8b668e8462de09248ac52c04c6ed9c9415837a24
